version: '3.0'
services:
  test:
    image: mikeandnick/mm-dev
    container_name: mm-test
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    command: npm run test
    depends_on:
      - postgres-db-test
  postgres-db-test:
    image: mikeandnick/mm-postgres
    container_name: mm-test-database
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=mmadmin
      - POSTGRES_DB=mmdb
    volumes:
      - test-db-volume:/var/lib/postgresql/data
volumes:
  node_modules: {}
  test-db-volume: {}
